/**
 * Product data extracted from "Price Gift Sets.pdf" (Gift Sets Catalogue 2026-27).
 *
 * The PDF is a 50-slide deck: each slide is one supplier catalogue image with the
 * current price laid over it as PDF text. The underlying image carries NO price,
 * so cropping the extracted base image gives a clean product shot.
 *
 * Many slides show 2-8 DIFFERENT boxes. `crop` splits a slide into one region per
 * box - [x0, y0, x1, y1] as fractions of the base image - so each catalogue entry
 * gets its own image showing only that box, its code/title and its contents list.
 * `crop: null` means the whole slide is a single product.
 *
 * `price` is the supplier price printed on the slide. Selling price = price * 1.4
 * (ex-GST), the same rule used for the Diwali boxes (per Anand, 2026-09-12).
 */

export type GiftSet = {
  page: number // 1-based PDF page
  code: string // supplier code on the slide
  price: number // supplier price in INR (pre-markup)
  name: string
  desc: string
  items: string[]
  crop: [number, number, number, number] | null
}

/** Unique per-product key, used for image filenames (supplier codes repeat across slides). */
export const keyOf = (g: GiftSet) => `p${String(g.page).padStart(2, '0')}-${g.code.toLowerCase()}`

export const GIFT_SETS: GiftSet[] = [
  // ---- single-product slides ----
  { page: 2, code: 'B001', price: 590, crop: null,
    name: 'Premium 3-in-1 Gift Set - Notebook, Pen & Vacuum Bottle',
    desc: 'A5 PU notebook, metal pen and a 500 ml double-wall vacuum bottle presented in a premium gift box. Available in black, white and green.',
    items: ['PU notebook - A5, 192 pages, 80 GSM', 'Metal pen', 'Vacuum bottle - 500 ml, stainless steel, double wall', 'Premium gift box'] },

  { page: 3, code: 'B002', price: 790, crop: null,
    name: '4-in-1 Premium Gift Set - Flask, Pocket Notebook, Pen & Keychain',
    desc: 'Insulated 500 ml flask with an A5 pocket notebook, metal pen and metal keychain in a colour-matched box. Available in green, black and blue.',
    items: ['Premium insulated flask - 500 ml', 'A5 pocket notebook', 'Metal pen', 'Metal keychain'] },

  { page: 4, code: 'B003', price: 790, crop: null,
    name: '4-in-1 Gift Set - Coffee Mug, Flap Notebook, Pen & Keychain',
    desc: 'A 300 ml coffee mug paired with a flap-closure notebook, metal pen and metal keychain. Available in black and ivory.',
    items: ['Coffee mug - 300 ml', 'Metal keychain', 'Metal pen', 'Flap notebook'] },

  { page: 5, code: 'B004', price: 750, crop: null,
    name: '4-in-1 Gift Set - 350 ml Flask, Flap Notebook, Pen & Keychain',
    desc: 'Insulated 350 ml flask with a banded flap notebook, metal pen and metal keychain in a premium tray box. Available in white and black.',
    items: ['Insulated flask - 350 ml', 'Metal keychain', 'Metal pen', 'Flap notebook'] },

  { page: 6, code: 'B005', price: 650, crop: null,
    name: 'Premium 3-in-1 Gift Set - 350 ml Flask, Notebook & Pen',
    desc: 'Everyday desk trio of a 350 ml hot-and-cold flask, banded notebook and metal pen. Available in olive green, black and white.',
    items: ['Flask - 350 ml, hot & cold', 'Notebook', 'Metal pen', 'Premium packaging'] },

  { page: 7, code: 'B006', price: 650, crop: null,
    name: 'Premium 3-in-1 Gift Set - 500 ml Flask & Magnet-Lock Notebook',
    desc: 'A 500 ml insulated flask with an A5 magnet-lock notebook and metal pen in a premium presentation box. Also available in black.',
    items: ['Insulated flask - 500 ml, hot & cold', 'Notebook with magnet lock - A5', 'Metal pen', 'Premium gift box'] },

  { page: 8, code: 'B007', price: 890, crop: null,
    name: 'Premium 5-in-1 Desk Gift Set - Notebook, Organiser & Mobile Stand',
    desc: 'Executive desk set with an A5 notebook, metal pen, keychain, metal mobile stand and a desktop organiser tray. Available in grey-black and black-gold.',
    items: ['A5 notebook', 'Metal pen', 'Metal keychain', 'Metal mobile stand', 'Desktop organiser'] },

  { page: 9, code: 'B008', price: 830, crop: null,
    name: 'Premium 3-in-1 Gift Set - 750 ml Flask, Notebook & Pen',
    desc: 'Large 750 ml insulated flask with a premium banded notebook and metal pen. Available in white, grey and sage green.',
    items: ['Insulated flask - 750 ml, hot & cold', 'Premium notebook', 'Metal pen'] },

  { page: 10, code: 'B009', price: 755, crop: null,
    name: 'Premium 5-in-1 Gift Set - Flask, Wine Tumbler, Notebook, Pen & Keychain',
    desc: 'A 750 ml temperature flask with a 350 ml silver-ring tumbler, A5 notebook, metal pen and premium keychain. Available in white and black.',
    items: ['Temperature flask - 750 ml', 'Mug - 350 ml with silver ring, hot & cold', 'Metal pen, premium finish', 'Notebook - A5', 'Premium keychain'] },

  { page: 11, code: 'B010', price: 695, crop: null,
    name: 'Premium 5-in-1 Gift Set - Flask, Handle Mug, Notebook, Pen & Keychain',
    desc: 'A 750 ml temperature flask with a 350 ml handled steel mug, A5 notebook, metal pen and premium keychain. Available in white and black.',
    items: ['Temperature flask - 750 ml', 'Mug - 350 ml with silver ring, hot & cold', 'Metal pen, premium finish', 'Notebook - A5', 'Premium keychain'] },

  { page: 12, code: 'B012', price: 390, crop: null,
    name: '4-in-1 Gift Set - 500 ml Flask, Notebook, Pen & Keychain',
    desc: 'Colour-matched 500 ml temperature flask, A5 notebook, metal pen and keychain. Available in red, blue, black and white.',
    items: ['Temperature flask - 500 ml', 'Metal pen, premium finish', 'Notebook - A5', 'Keychain'] },

  { page: 13, code: 'B012A', price: 350, crop: null,
    name: '3-in-1 Gift Set - 500 ml Flask, Notebook & Pen',
    desc: 'Colour-matched 500 ml temperature flask with an A5 notebook and metal pen. Available in red, blue, white and black.',
    items: ['Temperature flask - 500 ml', 'Metal pen, premium finish', 'Notebook - A5'] },

  // ---- two-up slides ----
  { page: 14, code: 'B013', price: 3750, crop: [0.015, 0.195, 0.478, 1.0],
    name: 'Borosil Premium Gift Set - Trek Flask, Carvaan Mini & Ferrero Rocher',
    desc: 'Top-end hamper pairing a Borosil Trek 700 ml flask and Hike coffee tumbler with a Saregama Carvaan Mini and Ferrero Rocher.',
    items: ['Borosil Trek 700 ml', 'Saregama Carvaan Mini', 'Ferrero Rocher chocolate', 'Borosil Hike coffee tumbler'] },
  { page: 14, code: 'B014', price: 1750, crop: [0.478, 0.195, 0.99, 1.0],
    name: 'Borosil Premium Gift Set - Trek Flask, Notebook, Pen & Hike Mug',
    desc: 'Borosil Trek 700 ml flask and Hike coffee mug with an A5 premium notebook and metal pen in a black presentation box.',
    items: ['Borosil Trek 700 ml', 'A5 premium notebook', 'Metal pen', 'Borosil Hike coffee mug'] },

  { page: 15, code: 'B015', price: 1725, crop: [0.01, 0.195, 0.5, 1.0],
    name: 'Borosil Premium Gift Set - Trek Flask, Notebook, Pen & Coffeemate',
    desc: 'Borosil Trek 700 ml flask with a premium notebook, metal pen and Borosil Coffeemate tumbler.',
    items: ['Borosil Trek 700 ml', 'Premium notebook', 'Metal pen', 'Borosil Coffeemate'] },
  { page: 15, code: 'B016', price: 1050, crop: [0.5, 0.195, 0.99, 1.0],
    name: 'Borosil Premium Gift Set - Woven Notebook, Pen & Hike Tumbler',
    desc: 'Woven-texture premium notebook with a metal pen and Borosil Hike tumbler in a black gift box.',
    items: ['Premium notebook', 'Metal pen', 'Borosil Hike tumbler'] },

  { page: 16, code: 'B017', price: 1650, crop: [0.02, 0.2, 0.482, 1.0],
    name: 'Premium Gift Set - Power Bank Organiser & 450 ml Coffee Mug',
    desc: 'Executive organiser with a built-in 10000 mAh power bank, paired with a 450 ml premium coffee mug.',
    items: ['Organiser with power bank - 10000 mAh', 'Premium coffee mug - 450 ml', 'Easy to carry'] },
  { page: 16, code: 'B018', price: 1050, crop: [0.482, 0.2, 0.99, 1.0],
    name: 'Premium Gift Set - Traveller Bag & Borosil Coffeemate',
    desc: 'Compact traveller pouch with a Borosil Coffeemate tumbler in a black presentation box.',
    items: ['Traveller bag', 'Borosil Coffeemate'] },

  { page: 17, code: 'B019', price: 2175, crop: [0.01, 0.11, 0.5, 1.0],
    name: 'Joining Tech Gift Set - Wireless Keyboard, Mouse, Power Bank & Speaker',
    desc: 'Onboarding kit with a wireless keyboard and mouse, MagSafe wireless charging power bank and a Bluetooth speaker.',
    items: ['Wireless keyboard', 'Wireless mouse', 'MagSafe wireless charging power bank - 10,000 mAh', 'Bluetooth speaker'] },
  { page: 17, code: 'B020', price: 2250, crop: [0.5, 0.11, 0.99, 1.0],
    name: 'Travel Tech Gift Set - Power Bank, Tracker, Earphone & Pouch',
    desc: 'Travel kit with a 10,000 mAh power bank, item tracker, multi-country charger, wired earphone and a zip travel pouch.',
    items: ['Power bank - 10,000 mAh', 'Tracker', 'Wired earphone', 'Multi country charger', 'Travel pouch'] },

  { page: 18, code: 'B021', price: 950, crop: [0.02, 0.225, 0.5, 1.0],
    name: '6-in-1 Golden Gift Set - Steel Bottle, Notebook, Mug & Mobile Stand',
    desc: 'Black-and-gold six-piece set with a 750 ml steel bottle, A5 notebook, 400 ml insulated mug and a metal mobile stand.',
    items: ['Steel bottle - 750 ml', 'A5 notebook', 'Metal pen', 'Metal keychain', 'Insulated mug - 400 ml', 'Metal mobile stand'] },
  { page: 18, code: 'B022', price: 1050, crop: [0.5, 0.225, 0.99, 1.0],
    name: '6-in-1 Cork Gift Set - Flask, Ceramic Mug, Notebook & Card Holder',
    desc: 'Cork-accented six-piece set with a 500 ml insulated flask, ceramic mug, notebook, card holder, pen and keychain.',
    items: ['Notebook', 'Metal pen', 'Card holder', 'Key chain', 'Ceramic mug', 'Insulated flask - 500 ml'] },

  { page: 19, code: 'V932', price: 450, crop: [0.0, 0.0, 0.5, 1.0],
    name: '3-in-1 Gift Set - A5 Notebook, Pen & Heavy Mobile Stand',
    desc: 'Woven-texture A5 notebook with a metal pen and a heavy premium mobile stand in a flap gift box.',
    items: ['Premium A5 notebook', 'Metal pen', 'Heavy premium mobile stand', 'Premium flap box'] },
  { page: 19, code: 'V930', price: 1160, crop: [0.5, 0.0, 1.0, 1.0],
    name: '3-in-1 Gift Set - Wireless Charging Digital Clock, Notebook & Pen',
    desc: 'Desk set built around a digital clock with wireless charging, plus a pocket notebook and metal pen.',
    items: ['Digital clock with wireless charging', 'Pocket notebook', 'Metal pen'] },

  { page: 20, code: 'V929', price: 1130, crop: [0.0, 0.0, 0.469, 1.0],
    name: 'Premium Grey 4-in-1 Gift Set - Notebook, Pen, Keychain & Flask',
    desc: 'Grey magnetic-flap box with an A5 notebook, metal pen, metal keychain and insulated flask.',
    items: ['A5 size notebook', 'Metal pen', 'Metal keychain', 'Insulated flask'] },
  { page: 20, code: 'V928', price: 1135, crop: [0.469, 0.0, 1.0, 1.0],
    name: 'Premium 4-in-1 Gift Set - 450 ml Coffee Mug, Notebook, Pen & Keychain',
    desc: 'Black magnetic-flap box with a 450 ml coffee mug, premium notebook, metal pen and metal keychain.',
    items: ['Coffee mug - 450 ml', 'Metal keychain', 'Metal pen', 'Premium notebook'] },

  { page: 21, code: 'V916', price: 1100, crop: [0.0, 0.0, 0.5, 1.0],
    name: 'Wireless Earphone & Portable Fan Gift Set',
    desc: 'Noise Airwave over-ear wireless headphones with a mini portable hand fan in a cream presentation box.',
    items: ['Noise Airwave wireless earphone', 'Mini portable hand fan'] },
  { page: 21, code: 'V906', price: 1200, crop: [0.5, 0.0, 1.0, 1.0],
    name: 'Neck Massager & MagSafe Power Bank Gift Set',
    desc: 'Cordless neck massager paired with a MagSafe wireless power bank in a navy presentation box.',
    items: ['Neck massager', 'MagSafe power bank'] },

  { page: 22, code: 'V920', price: 2200, crop: [0.0, 0.0, 0.48, 1.0],
    name: 'Executive Organiser Gift Set - 8000 mAh Power Bank, Flask & Pen Drive',
    desc: 'Green leatherette organiser with an 8000 mAh wireless-charging power bank, insulated flask, metal pen and pen drive.',
    items: ['Power bank organiser - 8000 mAh battery', 'Wireless charging', 'Metal pen', 'Insulated flask', 'Pen drive'] },
  { page: 22, code: 'V909', price: 850, crop: [0.48, 0.0, 1.0, 1.0],
    name: '4-in-1 Gift Set - Insulated Flask, A5 Notebook, Mobile Stand & Pen',
    desc: 'Grey presentation case with an insulated flask, A5 soft PU notebook, heavy mobile stand and metal pen.',
    items: ['Insulated flask', 'A5 soft PU notebook', 'Heavy mobile stand', 'Metal pen'] },

  { page: 23, code: 'V912', price: 1250, crop: [0.0, 0.0, 0.572, 0.8],
    name: 'Premium 4-in-1 Gift Set - 10,000 mAh MagSafe Power Bank & Notebook',
    desc: 'Patterned flip box with a 10,000 mAh MagSafe wireless power bank, premium notebook, mobile stand and metal pen.',
    items: ['MagSafe power bank - 10,000 mAh, wireless', 'Premium notebook', 'Mobile stand', 'Metal pen'] },
  { page: 23, code: 'V926', price: 775, crop: [0.572, 0.0, 1.0, 0.8],
    name: '4-in-1 Gift Set - Notebook, Pen, MagSafe Wallet & Keychain with Bag',
    desc: 'Notebook, metal pen, MagSafe mobile wallet and keychain presented with a matching gift bag. Available in grey and tan.',
    items: ['Note book', 'Metal pen', 'MagSafe mobile wallet', 'Key chain', 'Matching gift bag'] },

  { page: 24, code: 'B023', price: 750, crop: [0.01, 0.05, 0.5, 0.83],
    name: 'Premium Gift Set - A5 Texture Notebook, Pen & 450 ml Coffee Tumbler',
    desc: 'Two-tone A5 texture notebook with a metal pen and a 450 ml premium coffee tumbler.',
    items: ['A5 texture notebook', 'Metal pen', 'Premium coffee tumbler - 450 ml'] },
  { page: 24, code: 'B024', price: 495, crop: [0.5, 0.05, 0.99, 0.83],
    name: 'Premium Gift Set - Borosilicate Glass Bottle, World Map Notebook & Pen',
    desc: 'A 750 ml borosilicate glass bottle with a sleeve, world-map notebook and metal pen.',
    items: ['Borosilicate glass bottle - 750 ml', 'World map notebook', 'Metal pen'] },

  { page: 25, code: 'B025', price: 1550, crop: [0.01, 0.2, 0.5, 0.86],
    name: 'Premium 5-in-1 Gift Set - Foldable Notebook, Pen Stand & Ashoka Stambh',
    desc: 'Tan executive set with an A5 foldable notebook, premium metal pen, metal hand pen stand, keychain and a copper-finish Ashoka Stambh.',
    items: ['A5 foldable notebook', 'Premium metal pen', 'Metal hand pen stand', 'Metal keychain', 'Ashoka Stambh'] },
  { page: 25, code: 'B026', price: 750, crop: [0.5, 0.2, 0.99, 0.86],
    name: 'Premium 4-in-1 Gift Set - Notebook, Pen, Keychain & Temp-Display Mug',
    desc: 'A5 notebook with a metal pen, metal keychain and a steel coffee mug with temperature display.',
    items: ['A5 note book', 'Metal pen', 'Metal key chain', 'Coffee mug with temp display'] },

  { page: 26, code: 'B027', price: 750, crop: [0.01, 0.12, 0.5, 0.95],
    name: '4-in-1 Gift Set - Black Notebook, Pen, Keychain & Coffee Mug',
    desc: 'Black flap notebook with a metal pen, keychain and a ribbed coffee mug in a wooden-finish tray.',
    items: ['Coffee mug', 'Premium note book', 'Metal pen', 'Key chain'] },
  { page: 26, code: 'B028', price: 750, crop: [0.5, 0.12, 0.99, 0.95],
    name: '4-in-1 Gift Set - Fabric Notebook, Pen, Keychain & Coffee Mug',
    desc: 'Grey fabric-bound notebook with a metal pen, keychain and a white ribbed coffee mug in a wooden-finish tray.',
    items: ['Coffee mug', 'Premium note book', 'Metal pen', 'Key chain'] },

  // ---- 2x2 slide ----
  { page: 27, code: 'B031', price: 595, crop: [0.0, 0.0, 0.494, 0.499],
    name: 'Premium 3-in-1 Gift Set - Bamboo Notebook, Pen & 350 ml Coffee Mug',
    desc: 'Sustainable trio of a bamboo-cover notebook, metal pen and a 350 ml bamboo-base coffee mug.',
    items: ['Bamboo note book', 'Metal pen', 'Coffee mug - 350 ml'] },
  { page: 27, code: 'B032', price: 650, crop: [0.494, 0.0, 1.0, 0.499],
    name: 'Premium 3-in-1 Gift Set - Cork Notebook, Pen & 500 ml Coffee Mug',
    desc: 'Cork-accented set with an A5 cork notebook, metal pen and a 500 ml cork-base coffee mug.',
    items: ['Coffee mug - 500 ml', 'Metal pen', 'A5 cork note book'] },
  { page: 27, code: 'B029', price: 535, crop: [0.0, 0.499, 0.494, 1.0],
    name: '3-in-1 Gift Set - Notebook, Pen & 500 ml Coffee Tumbler',
    desc: 'Ribbed black notebook with a metal pen and a 500 ml grip coffee tumbler.',
    items: ['Note book', 'Metal pen', 'Coffee tumbler - 500 ml'] },
  { page: 27, code: 'B030', price: 465, crop: [0.494, 0.499, 1.0, 1.0],
    name: '3-in-1 Gift Set - Notebook, Pen & 350 ml Coffee Mug',
    desc: 'Black notebook with a metal clasp, metal pen and a 350 ml flip-lid coffee mug.',
    items: ['Note book', 'Metal pen', 'Coffee mug - 350 ml'] },

  { page: 28, code: 'B033', price: 1150, crop: [0.0, 0.08, 0.51, 1.0],
    name: 'Premium 4-in-1 Tech Gift Set - Power Bank, Mouse, Flash Drive & Pen',
    desc: 'Tech kit with a 10000 mAh dual-output power bank, wireless mouse, 8GB swivel flash drive and a metal pen.',
    items: ['8GB swivel USB flash drive', 'Power bank - 10000 mAh, dual USB output', 'Wireless mouse', 'Metal pen'] },
  { page: 28, code: 'B034', price: 850, crop: [0.51, 0.05, 1.0, 1.0],
    name: 'Premium 3-in-1 Gift Set - 500 ml Flask, Pen & A5 Flap Notebook',
    desc: 'Wood-base 500 ml insulated flask with a metal pen and an A5 flap notebook.',
    items: ['Insulated flask - 500 ml', 'Metal pen', 'Flap note book - A5 size'] },

  { page: 29, code: 'B035', price: 545, crop: [0.0, 0.0, 0.465, 1.0],
    name: 'Premium 3-in-1 Gift Set - Glass Bottle with Silicone Sleeve & Notebook',
    desc: 'Borosilicate glass bottle with a silicone sleeve, metal pen and a navy notebook.',
    items: ['Borosilicate glass bottle with silicon sleeve', 'Metal pen', 'Note book'] },
  { page: 29, code: 'B036', price: 890, crop: [0.465, 0.0, 1.0, 1.0],
    name: 'Premium 4-in-1 Drinkware Gift Set - Flask, Beer Tumbler & Keychain',
    desc: 'Drinkware set with a 750 ml insulated flask, beer tumbler, coffee-and-beer tumbler and a metal keychain.',
    items: ['Insulated flask - 750 ml', 'Metal key chain', 'Beer tumbler', 'Coffee & beer tumbler'] },

  { page: 30, code: 'B037', price: 1290, crop: [0.0, 0.0, 0.5, 0.91],
    name: '6-in-1 Tech Gift Set - Power Bank, Wireless Mouse & A5 Notebook',
    desc: 'Six-piece tech set with a wireless mouse, 10000 mAh power bank, 3-in-1 charging cable, A5 fabric notebook, metal pen and keychain.',
    items: ['Wireless mouse', 'Power bank - 10000 mAh', 'Multi charging cable - 3-in-1 fast charging', 'A5 notebook - premium fabric cover', 'Metal pen', 'Keychain'] },
  { page: 30, code: 'B038', price: 850, crop: [0.5, 0.0, 1.0, 0.91],
    name: '4-in-1 Conference Gift Set - A4 Folder, Pen Stand & Paper Weight',
    desc: 'Vegan-leather cane-design conference set with an A4 folder, pen stand, paper weight and a things-to-do pad.',
    items: ['Conference folder (A4) - premium vegan leather with cane design', 'Pen stand', 'Paper weight', 'Things to do pad'] },

  { page: 31, code: 'B060', price: 2050, crop: [0.0, 0.0, 0.435, 0.63],
    name: 'Premium 4-in-1 Bamboo Desk Set - Charging Mouse Pad, Clock & Speaker',
    desc: 'Bamboo desk set with a wireless-charging mouse pad with logo glow, wooden digital clock, Bluetooth speaker and a bamboo charging cable set.',
    items: ['Wireless charging mouse pad with logo glow', 'Wooden digital clock', 'Bluetooth speaker', 'Bamboo wireless charging cable set'] },
  { page: 31, code: 'B061', price: 2490, crop: [0.435, 0.0, 1.0, 0.63],
    name: 'Premium 7-in-1 Bamboo Desk Set - Ashok Stambh, Clock & Speaker',
    desc: 'Seven-piece bamboo desk set with an Ashok Stambh, wireless-charging mouse pad, charging pad, digital clock, metal pen, Bluetooth speaker and cork notebook.',
    items: ['Ashok Stambh', 'Wireless charging mouse pad with LED logo', 'Bamboo wireless charging pad', 'Digital clock', 'Metal pen', 'Bluetooth speaker', 'Cork note book'] },

  { page: 32, code: 'B063', price: 990, crop: [0.0, 0.0, 0.505, 0.95],
    name: '3-in-1 Bamboo Gift Set - Bamboo Flask & Two Mugs',
    desc: 'Natural bamboo flask with two bamboo tea/coffee mugs in a kraft gift box.',
    items: ['Bamboo flask', '2 tea/coffee mugs'] },
  { page: 32, code: 'B064', price: 595, crop: [0.505, 0.0, 1.0, 0.95],
    name: '3-in-1 Eco Friendly Gift Set - Wheat Straw Mugs & Glass Bottle',
    desc: 'Two wheat-straw mugs with a glass bottle in a jute cover, packed in a kraft gift box.',
    items: ['2 wheat straw mugs', '1 glass bottle with jute cover'] },

  { page: 33, code: 'B065', price: 1450, crop: [0.0, 0.0, 0.515, 1.0],
    name: 'Eco Friendly 5-in-1 Gift Set - Glass Mug, Bamboo Clock & Cable Set',
    desc: 'Sustainable desk set with a straw glass mug, bamboo digital clock, bamboo all-in-1 cable set, cork-and-bamboo notebook and a double-wall borosilicate bottle.',
    items: ['Glass mug with straw', 'Bamboo digital clock', 'Bamboo all-in-1 cable set', 'Cork & bamboo texture notebook', 'Double wall borosilicate bottle'] },
  { page: 33, code: 'B066', price: 2100, crop: [0.515, 0.0, 1.0, 1.0],
    name: 'Smart & Sustainable Gift Set - Smartwatch, Travel Tumbler & Ferrero',
    desc: 'Cork-accented set with a double-walled travel tumbler, a smartwatch with 1.9" HD display, Ferrero Rocher pack and a notebook-and-pen combination.',
    items: ['Double walled travel tumbler', 'Smartwatch with 1.9" HD display', 'Ferrero Rocher chocolate pack', 'Combination notebook & pen'] },

  // ---- three-up slide ----
  { page: 34, code: 'B067', price: 1050, crop: [0.01, 0.13, 0.34, 0.94],
    name: 'Eco Friendly 6-in-1 Bamboo Gift Set - Flask, Mug & Card Holder',
    desc: 'All-bamboo six-piece set with a flask, mug, notebook, pen, keychain and card holder.',
    items: ['Bamboo flask', 'Bamboo mug', 'Bamboo notebook', 'Bamboo pen', 'Bamboo keychain', 'Bamboo card holder'] },
  { page: 34, code: 'B068', price: 1495, crop: [0.34, 0.13, 0.665, 0.94],
    name: 'Eco Friendly 6-in-1 Bamboo Gift Set - Flask, Mug & Bluetooth Speaker',
    desc: 'All-bamboo six-piece set with a flask, mug, notebook, pen, keychain and a bamboo Bluetooth speaker.',
    items: ['Bamboo flask', 'Bamboo mug', 'Bamboo notebook', 'Bamboo pen', 'Bamboo keychain', 'Bamboo Bluetooth speaker'] },
  { page: 34, code: 'B069', price: 1125, crop: [0.665, 0.13, 0.995, 0.94],
    name: 'Eco Friendly 6-in-1 Bamboo Gift Set - Flask, Mug, Notebook & Keychain',
    desc: 'All-bamboo six-piece set with a flask, mug, notebook, pen, keychain and card holder in a black tray box.',
    items: ['Bamboo flask', 'Bamboo mug', 'Bamboo notebook', 'Bamboo pen', 'Bamboo keychain', 'Bamboo card holder'] },

  // ---- 2x2 slide ----
  { page: 35, code: 'B071', price: 625, crop: [0.0, 0.0, 0.497, 0.485],
    name: '3-in-1 Bamboo Gift Set - Notebook, Flask, Pen & Keychain',
    desc: 'Bamboo-cover notebook with a bamboo flask, metal pen and bamboo keychain.',
    items: ['Bamboo notebook', 'Bamboo flask', 'Metal pen', 'Bamboo keychain'] },
  { page: 35, code: 'B072', price: 595, crop: [0.497, 0.0, 1.0, 0.485],
    name: '3-in-1 Eco Friendly Gift Set - Bamboo Notebook, Flask & Pen',
    desc: 'Bamboo notebook, bamboo flask and bamboo pen in a black tray gift box.',
    items: ['Bamboo notebook', 'Bamboo flask', 'Bamboo pen'] },
  { page: 35, code: 'B073', price: 410, crop: [0.0, 0.485, 0.497, 0.905],
    name: '3-in-1 Natural Gift Set - Bamboo Notebook, Glass Bottle & Pen',
    desc: 'Bamboo notebook with a glass bottle in a jute cover and a bamboo pen.',
    items: ['Bamboo notebook', 'Glass bottle with jute cover', 'Bamboo pen'] },
  { page: 35, code: 'B074', price: 445, crop: [0.497, 0.485, 1.0, 0.905],
    name: '3-in-1 Sustainable Gift Set - Cork Notebook, Wheat Straw Cup & Pen',
    desc: 'Bamboo-and-cork notebook with a wheat straw cup with cork sleeve and a bamboo pen.',
    items: ['Bamboo & cork notebook', 'Wheat straw cup with cork sleeve', 'Bamboo pen'] },

  { page: 36, code: 'B075', price: 1050, crop: [0.0, 0.0, 0.505, 0.88],
    name: '4-in-1 Premium Eco Gift Set - Bamboo Notebook, Flask, Mug & Keychain',
    desc: 'Bamboo notebook with a premium black flask, bamboo pen, metal keychain and a bamboo-base mug.',
    items: ['Bamboo notebook', 'Premium flask', 'Bamboo pen', 'Metal keychain', 'Bamboo mug'] },
  { page: 36, code: 'B076', price: 370, crop: [0.505, 0.0, 1.0, 0.88],
    name: '3-in-1 Natural Gift Set - Cork Notebook, Pen & Glass Mason Jar',
    desc: 'Bamboo-and-cork notebook with a bamboo pen and a glass mason jar with bamboo lid and straw.',
    items: ['Bamboo & cork notebook', 'Bamboo pen', 'Glass mason jar with bamboo lid & straw'] },

  // ---- four-up slides ----
  { page: 37, code: 'B077', price: 390, crop: [0.005, 0.26, 0.245, 0.83],
    name: '3-in-1 Bamboo Gift Set - Oak Notebook, Card Holder & Pen',
    desc: 'Oak-finish notebook with a bamboo card holder, bamboo pen and keychain in a black tray box.',
    items: ['Oak finish notebook', 'Bamboo card holder', 'Bamboo pen', 'Keychain'] },
  { page: 37, code: 'B078', price: 380, crop: [0.25, 0.26, 0.49, 0.83],
    name: '3-in-1 Bamboo Gift Set - Bamboo Notebook, Card Holder & Pen',
    desc: 'Bamboo-cover notebook with a bamboo card holder, bamboo pen and keychain in a black tray box.',
    items: ['Bamboo notebook', 'Bamboo card holder', 'Bamboo pen', 'Keychain'] },
  { page: 37, code: 'B079', price: 375, crop: [0.495, 0.26, 0.735, 0.83],
    name: '3-in-1 Cork Gift Set - Black & Cork Notebook, Card Holder & Pen',
    desc: 'Two-tone black-and-cork notebook with a cork card holder, pen and keychain in a black tray box.',
    items: ['Black & cork notebook', 'Cork card holder', 'Metal pen', 'Keychain'] },
  { page: 37, code: 'B080', price: 375, crop: [0.74, 0.26, 0.985, 0.83],
    name: '3-in-1 Cork Gift Set - White & Cork Notebook, Card Holder & Pen',
    desc: 'Two-tone white-and-cork notebook with a cork card holder, bamboo pen and keychain in a black tray box.',
    items: ['White & cork notebook', 'Cork card holder', 'Bamboo pen', 'Keychain'] },

  { page: 38, code: 'B081', price: 375, crop: [0.005, 0.27, 0.245, 0.82],
    name: '3-in-1 Cork Gift Set - Cork Notebook, Card Holder & Pen',
    desc: 'Full-cork notebook with a cork card holder, metal pen and keychain in a black tray box.',
    items: ['Cork notebook', 'Cork card holder', 'Metal pen', 'Keychain'] },
  { page: 38, code: 'B082', price: 380, crop: [0.25, 0.27, 0.49, 0.82],
    name: '3-in-1 Cork & Bamboo Gift Set - Notebook, Card Holder & Pen',
    desc: 'Bamboo-and-cork notebook with a cork card holder, bamboo pen and keychain in a black tray box.',
    items: ['Bamboo & cork notebook', 'Cork card holder', 'Bamboo pen', 'Keychain'] },
  { page: 38, code: 'B083', price: 435, crop: [0.495, 0.27, 0.735, 0.82],
    name: '3-in-1 Executive Gift Set - Black Card Holder, Notebook & Pen',
    desc: 'Black executive notebook with a metal card holder, metal pen and keychain in a black tray box.',
    items: ['Black notebook', 'Metal card holder', 'Metal pen', 'Keychain'] },
  { page: 38, code: 'B084', price: 425, crop: [0.74, 0.27, 0.985, 0.82],
    name: '3-in-1 Executive Gift Set - Gold Card Holder, Black Notebook & Pen',
    desc: 'Black notebook with a gold-finish card holder and clasp, metal pen and keychain in a black tray box.',
    items: ['Black notebook with gold clasp', 'Gold finish card holder', 'Metal pen', 'Keychain'] },

  { page: 39, code: 'B085', price: 465, crop: [0.01, 0.19, 0.505, 0.9],
    name: '3-in-1 Premium Gift Set - Tan Notebook, Card Holder & Keychain',
    desc: 'Tan textured notebook with a leather-finish card holder, metal pen and metal keychain.',
    items: ['Tan textured notebook', 'Card holder', 'Metal pen', 'Metal keychain'] },
  { page: 39, code: 'B086', price: 465, crop: [0.505, 0.19, 0.99, 0.9],
    name: '3-in-1 Premium Gift Set - Black Notebook, Card Holder & Keychain',
    desc: 'Black textured notebook with a leather-finish card holder, metal pen and metal keychain.',
    items: ['Black textured notebook', 'Card holder', 'Metal pen', 'Metal keychain'] },

  { page: 40, code: 'B087', price: 415, crop: [0.005, 0.26, 0.245, 0.8],
    name: '3-in-1 Executive Gift Set - Tan Woven Notebook & Card Holder',
    desc: 'Tan woven-texture notebook with a metal card holder, pen and keychain in a black tray box.',
    items: ['Tan woven notebook', 'Metal card holder', 'Metal pen', 'Keychain'] },
  { page: 40, code: 'B088', price: 390, crop: [0.25, 0.26, 0.49, 0.8],
    name: '3-in-1 Executive Gift Set - Brown Ribbed Notebook & Card Holder',
    desc: 'Brown ribbed notebook with a tan card holder, metal pen and keychain in a black tray box.',
    items: ['Brown ribbed notebook', 'Card holder', 'Metal pen', 'Keychain'] },
  { page: 40, code: 'B089', price: 435, crop: [0.495, 0.26, 0.735, 0.8],
    name: '3-in-1 Executive Gift Set - Brown Suede Notebook & Card Holder',
    desc: 'Brown suede-finish notebook with a black card holder, metal pen and keychain in a black tray box.',
    items: ['Brown suede notebook', 'Card holder', 'Metal pen', 'Keychain'] },
  { page: 40, code: 'B090', price: 390, crop: [0.74, 0.26, 0.985, 0.8],
    name: '3-in-1 Executive Gift Set - Black Notebook, Card Holder & Keychain',
    desc: 'Black flap notebook with a metal card holder, metal pen and keychain in a black tray box.',
    items: ['Black flap notebook', 'Metal card holder', 'Metal pen', 'Keychain'] },

  { page: 41, code: 'B091', price: 465, crop: [0.01, 0.19, 0.495, 0.885],
    name: '3-in-1 Premium Gift Set - Charcoal Notebook, Card Holder & Keychain',
    desc: 'Charcoal notebook with a metal card holder, metal pen and keychain in a black tray box.',
    items: ['Charcoal notebook', 'Metal card holder', 'Metal pen', 'Keychain'] },
  { page: 41, code: 'B092', price: 465, crop: [0.495, 0.19, 0.99, 0.885],
    name: '3-in-1 Premium Gift Set - Stone Grey Notebook, Card Holder & Keychain',
    desc: 'Stone grey notebook with a metal card holder, metal pen and keychain in a black tray box.',
    items: ['Stone grey notebook', 'Metal card holder', 'Metal pen', 'Keychain'] },

  { page: 42, code: 'B093', price: 465, crop: [0.01, 0.19, 0.5, 0.855],
    name: '3-in-1 Premium Gift Set - Two-Tone Grey Notebook & Card Holder',
    desc: 'Two-tone grey and black notebook with a metal card holder, metal pen and keychain.',
    items: ['Two-tone grey notebook', 'Metal card holder', 'Metal pen', 'Keychain'] },
  { page: 42, code: 'B094', price: 450, crop: [0.5, 0.19, 0.99, 0.855],
    name: '3-in-1 Premium Gift Set - Beige Notebook, Card Holder & Keychain',
    desc: 'Beige fabric-finish notebook with a metal card holder, metal pen and keychain.',
    items: ['Beige notebook', 'Metal card holder', 'Metal pen', 'Keychain'] },

  { page: 43, code: 'B110', price: 295, crop: [0.014, 0.155, 0.239, 0.755],
    name: 'Natural Cork Notebook Gift Set - White Vegan Leather Cover',
    desc: 'A5 notebook with a cork and white vegan-leather cover, cork barrel pen and cork keychain in a premium gift box.',
    items: ['A5 notebook with cork & white vegan leather cover', 'Cork barrel pen with metal clip', 'Cork & metal keychain', 'Premium gift box'] },
  { page: 43, code: 'B111', price: 295, crop: [0.259, 0.155, 0.487, 0.755],
    name: 'Natural Cork Notebook Gift Set - Bamboo Cover',
    desc: 'A5 notebook with a cork and bamboo cover, cork barrel pen and cork keychain in a premium gift box.',
    items: ['A5 notebook with cork & bamboo cover', 'Cork barrel pen with metal clip', 'Cork & metal keychain', 'Premium gift box'] },
  { page: 43, code: 'B112', price: 295, crop: [0.508, 0.155, 0.736, 0.755],
    name: 'Natural Cork Notebook Gift Set - Grey Vegan Leather Cover',
    desc: 'A5 notebook with a cork and grey vegan-leather cover, cork barrel pen and cork keychain in a premium gift box.',
    items: ['A5 notebook with cork & grey vegan leather cover', 'Cork barrel pen with metal clip', 'Cork & metal keychain', 'Premium gift box'] },
  { page: 43, code: 'B113', price: 280, crop: [0.757, 0.155, 0.985, 0.755],
    name: 'Natural Cork Notebook Gift Set - Full Cork Cover',
    desc: 'A5 notebook with a full cork cover, cork barrel pen and cork keychain in a premium gift box.',
    items: ['A5 notebook with cork cover', 'Cork barrel pen with metal clip', 'Cork & metal keychain', 'Premium gift box'] },

  { page: 44, code: 'B112', price: 315, crop: [0.012, 0.14, 0.239, 0.805],
    name: 'Wooden Touch 3-in-1 Gift Set - Notebook, Pen & Keychain',
    desc: 'A5 hard-cover notebook with a wooden texture and magnetic strap, wooden-finish metal pen and a wooden keychain.',
    items: ['A5 notebook - hard cover with wooden texture and magnetic strap', 'Metal pen - wooden finish', 'Wooden keychain with metal ring'] },
  { page: 44, code: 'B113', price: 310, crop: [0.257, 0.14, 0.491, 0.805],
    name: 'Bamboo Elegance 3-in-1 Gift Set - Notebook, Pen & Keychain',
    desc: 'A5 bamboo-cover notebook with a magnetic closure, wooden-finish metal pen and a bamboo keychain.',
    items: ['A5 notebook - bamboo cover with magnetic closure', 'Metal pen - wooden finish', 'Bamboo keychain with metal ring'] },
  { page: 44, code: 'B114', price: 285, crop: [0.51, 0.14, 0.742, 0.805],
    name: 'Urban Leather 3-in-1 Gift Set - World Map Notebook, Pen & Keychain',
    desc: 'A5 premium PU leather notebook with a world-map design, sleek metal pen and a metal-and-leather keychain.',
    items: ['A5 notebook - premium PU leather cover with world design', 'Metal pen', 'Metal & leather keychain'] },
  { page: 44, code: 'B115', price: 350, crop: [0.758, 0.14, 0.992, 0.805],
    name: 'Classic Brown 3-in-1 Gift Set - Notebook, Pen & Keychain',
    desc: 'A5 hard-cover notebook with a textured finish and magnetic clasp, metal pen and a leather keychain.',
    items: ['A5 notebook - hard cover with textured finish and magnetic clasp', 'Metal pen', 'Leather keychain with metal ring'] },

  { page: 45, code: 'B116', price: 315, crop: [0.012, 0.135, 0.239, 0.81],
    name: '3-in-1 Gift Set - World Map Notebook, Pen & Keychain',
    desc: 'A5 hard-cover notebook with a world-map design, metal pen and a metal-and-leather keychain in a premium gift box.',
    items: ['A5 notebook - hard cover with world map design', 'Metal pen', 'Metal & leather keychain', 'Premium gift box'] },
  { page: 45, code: 'B117', price: 310, crop: [0.257, 0.135, 0.491, 0.81],
    name: '3-in-1 Gift Set - Blue PU Pocket Notebook, Pen & Keychain',
    desc: 'A5 premium PU leather notebook with a pocket design, metal pen and a metal-and-leather keychain in a premium gift box.',
    items: ['A5 notebook - premium PU leather cover with pocket design', 'Metal pen', 'Metal & leather keychain', 'Premium gift box'] },
  { page: 45, code: 'B118', price: 355, crop: [0.51, 0.135, 0.742, 0.81],
    name: '3-in-1 Gift Set - Textured Stripe Notebook, Pen & Keychain',
    desc: 'A5 PU leather notebook with a textured stripe and magnetic clasp, metal pen and a metal-and-leather keychain.',
    items: ['A5 notebook - PU leather cover with textured stripe & magnetic clasp', 'Metal pen', 'Metal & leather keychain', 'Premium gift box'] },
  { page: 45, code: 'B119', price: 355, crop: [0.758, 0.135, 0.992, 0.81],
    name: '3-in-1 Gift Set - Suede Finish Notebook, Pen & Keychain',
    desc: 'A5 PU leather notebook with a suede finish and magnetic clasp, metal pen and a metal-and-leather keychain.',
    items: ['A5 notebook - PU leather cover with suede finish & magnetic clasp', 'Metal pen', 'Metal & leather keychain', 'Premium gift box'] },

  { page: 46, code: 'B120', price: 290, crop: [0.012, 0.13, 0.239, 0.815],
    name: '3-in-1 Executive Black Gift Set - Notebook, Pen & Keychain',
    desc: 'A5 premium PU leather notebook in black with a metal pen and a metal-and-leather keychain in a stylish gift box.',
    items: ['A5 notebook - premium PU leather cover with smooth finish', 'Metal pen', 'Metal & leather keychain', 'Stylish gift box'] },
  { page: 46, code: 'B121', price: 335, crop: [0.257, 0.13, 0.491, 0.815],
    name: '3-in-1 Executive Blue Gift Set - Notebook, Pen & Keychain',
    desc: 'A5 premium PU leather notebook in blue with a metal pen and a metal-and-leather keychain in a stylish gift box.',
    items: ['A5 notebook - premium PU leather cover with smooth finish', 'Metal pen', 'Metal & leather keychain', 'Stylish gift box'] },
  { page: 46, code: 'B122', price: 325, crop: [0.51, 0.13, 0.742, 0.815],
    name: '3-in-1 Urban Grey Gift Set - Notebook, Pen & Keychain',
    desc: 'A5 premium PU leather notebook in grey with a metal clasp, metal pen and a metal-and-leather keychain.',
    items: ['A5 notebook - premium PU leather cover with smooth finish', 'Metal pen', 'Metal & leather keychain', 'Stylish gift box'] },
  { page: 46, code: 'B123', price: 290, crop: [0.758, 0.13, 0.992, 0.815],
    name: '3-in-1 Prestige Tan Gift Set - Notebook, Pen & Keychain',
    desc: 'A5 premium PU leather notebook in tan with a rose-gold metal pen and a metal-and-leather keychain.',
    items: ['A5 notebook - premium PU leather cover with smooth finish', 'Metal pen', 'Metal & leather keychain', 'Stylish gift box'] },

  { page: 47, code: 'B124', price: 250, crop: [0.012, 0.145, 0.239, 0.81],
    name: '2-in-1 Executive Tan Gift Set - Wood & Cork Notebook with Pen',
    desc: 'A5 notebook with a wood-and-cork finish cover and a matching cork barrel pen in an elegant black gift box.',
    items: ['A5 notebook - premium cover with wood & cork finish', 'Metal pen', 'Stylish gift box'] },
  { page: 47, code: 'B125', price: 270, crop: [0.257, 0.145, 0.491, 0.81],
    name: '2-in-1 Royal Blue Gift Set - Notebook & Pen',
    desc: 'A5 premium PU notebook in royal blue with an elegant finish and a matching metal pen.',
    items: ['A5 notebook - premium PU cover with elegant finish', 'Metal pen', 'Stylish gift box'] },
  { page: 47, code: 'B126', price: 270, crop: [0.51, 0.145, 0.742, 0.81],
    name: '2-in-1 Classic Black Gift Set - Notebook & Pen',
    desc: 'A5 premium PU notebook in black with a modern two-tone design and a matching metal pen.',
    items: ['A5 notebook - premium PU cover with modern design', 'Metal pen', 'Stylish gift box'] },
  { page: 47, code: 'B127', price: 275, crop: [0.758, 0.145, 0.992, 0.81],
    name: '2-in-1 Prestige Brown Gift Set - Notebook & Pen',
    desc: 'A5 premium PU notebook in brown with a textured finish and a rose-gold metal pen.',
    items: ['A5 notebook - premium PU cover with textured finish', 'Metal pen', 'Stylish gift box'] },

  { page: 48, code: 'B128', price: 280, crop: [0.012, 0.128, 0.239, 0.755],
    name: '2-in-1 Executive Tan Gift Set - Flap Notebook & Pen',
    desc: 'A5 premium PU notebook in tan with a smooth finish and flap closure, paired with a matching metal pen.',
    items: ['A5 notebook - premium PU cover with smooth finish', 'Metal pen'] },
  { page: 48, code: 'B129', price: 280, crop: [0.257, 0.128, 0.491, 0.755],
    name: '2-in-1 Executive Black Gift Set - Flap Notebook & Pen',
    desc: 'A5 premium PU notebook in black with a smooth finish and flap closure, paired with a matching metal pen.',
    items: ['A5 notebook - premium PU cover with smooth finish', 'Metal pen'] },
  { page: 48, code: 'B130', price: 285, crop: [0.51, 0.128, 0.742, 0.755],
    name: '2-in-1 Executive Blue Gift Set - Flap Notebook & Pen',
    desc: 'A5 premium PU notebook in blue with a smooth finish and flap closure, paired with a matching metal pen.',
    items: ['A5 notebook - premium PU cover with smooth finish', 'Metal pen'] },
  { page: 48, code: 'B131', price: 280, crop: [0.758, 0.128, 0.992, 0.755],
    name: '2-in-1 Executive White Gift Set - Flap Notebook & Pen',
    desc: 'A5 premium PU notebook in white with a smooth finish and flap closure, paired with a matching metal pen.',
    items: ['A5 notebook - premium PU cover with smooth finish', 'Metal pen'] },

  { page: 49, code: 'B132', price: 315, crop: [0.012, 0.135, 0.239, 0.775],
    name: '2-in-1 Executive Black Gift Set - Clip Notebook & Pen',
    desc: 'A5 premium PU notebook in black with a metal clip closure and front pocket, paired with a metal pen.',
    items: ['A5 notebook - premium PU cover with smooth finish', 'Metal pen'] },
  { page: 49, code: 'B133', price: 315, crop: [0.257, 0.135, 0.491, 0.775],
    name: '2-in-1 Executive Orange Gift Set - Notebook & Pen',
    desc: 'A5 premium PU notebook in orange with a metal clip closure, paired with a colour-matched metal pen.',
    items: ['A5 notebook - premium PU cover with smooth finish', 'Metal pen'] },
  { page: 49, code: 'B134', price: 310, crop: [0.51, 0.135, 0.742, 0.775],
    name: '2-in-1 Executive Grey Gift Set - Notebook & Pen',
    desc: 'A5 premium PU notebook in grey with a metal clip band, paired with a black metal pen.',
    items: ['A5 notebook - premium PU cover with smooth finish', 'Metal pen'] },
  { page: 49, code: 'B135', price: 310, crop: [0.758, 0.135, 0.992, 0.775],
    name: '2-in-1 Executive Brown Gift Set - Notebook & Pen',
    desc: 'A5 premium PU notebook in brown with a ribbed texture and metal clip band, paired with a matching metal pen.',
    items: ['A5 notebook - premium PU cover with smooth finish', 'Metal pen'] },

  { page: 50, code: 'B136', price: 295, crop: [0.012, 0.132, 0.239, 0.815],
    name: '2-in-1 Executive Black Striped Gift Set - Notebook & Pen',
    desc: 'A5 premium PU notebook in black with a striped texture panel, paired with a metal pen in an elegant gift box.',
    items: ['A5 notebook - premium PU cover with smooth finish', 'Metal pen', 'Elegant gift box'] },
  { page: 50, code: 'B137', price: 310, crop: [0.257, 0.132, 0.491, 0.815],
    name: '2-in-1 Executive Dark Grey Gift Set - Notebook & Pen',
    desc: 'A5 premium PU notebook in dark grey with a metal clasp, paired with a metal pen in an elegant gift box.',
    items: ['A5 notebook - premium PU cover with smooth finish', 'Metal pen', 'Elegant gift box'] },
  { page: 50, code: 'B138', price: 310, crop: [0.51, 0.132, 0.742, 0.815],
    name: '2-in-1 Executive Beige Gift Set - Notebook & Pen',
    desc: 'A5 premium PU notebook in beige with a metal clasp, paired with a rose-gold metal pen in an elegant gift box.',
    items: ['A5 notebook - premium PU cover with smooth finish', 'Metal pen', 'Elegant gift box'] },
  { page: 50, code: 'B139', price: 310, crop: [0.758, 0.132, 0.992, 0.815],
    name: '2-in-1 Executive Light Grey Gift Set - Notebook & Pen',
    desc: 'A5 premium PU notebook in light grey with a suede panel and metal clasp, paired with a metal pen.',
    items: ['A5 notebook - premium PU cover with smooth finish', 'Metal pen', 'Elegant gift box'] },
]
